agent:
  name: claude-agent
  system_prompt: "You are Claude, an AI assistant. Be concise and helpful."
  verbose: true
model:
  model: claude-3-haiku-20240307
  max_tokens: 1000
  temperature: 0.7
tools:
  enabled: []
